apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: spring-boot-app
  labels:
    name: spring-boot-app
  annotations:
    admission.stackrox.io/break-glass: ticket-1234
spec:
  runPolicy: Serial
  source:
    git:
      uri: https://github.com/codecentric/springboot-sample-app.git
    Type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamImage
        name: registry.access.redhat.com/ubi8/openjdk-11
      type: Source
  output:
    to:
      kind: ImageStreamTag
      name: spring-boot-app:latest